language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: Z6drHWBtszl2BgWwmhwasxOlwp/IlcbJjfwYlH8w5AywWT28uCA9lsvjbWZhna+eQ+Gpp+Ka++mcmKBIt3GHTj3u7uzTgSgCE10HYMZd2vbBxXKpM8NNFu+aZ9vhd9xJLyq/86KF4nSlrn+e/HWpopnKd4zDz8F4Ou3xfx+mYGCJS1mNuLQDYBF4aw6Dqr6yvCSSQdfTMgItxzCvzAzmP0rJWR2uJA9XP/Q33c5D/+RSYOnn6XgdRvcRlsQRuoRjPZ//DQMQzbmVEBvonpmZUp7Kv/B1D+bPbvs8JW8mE2cPT/i3ssUqgGiq4Ezgp6s+ERikA5uFxKmNDTcKUjLYQjITgZjNmuYmzeUrqqQ2AVTfM/u5xCh+6sKSxhOOZ91iGfAr1c3dCCacKkZH4uxvqE67G7Kvp1l4J3CuPr8tZkSH/zB7G8+hk5cNEJwlJDcOM6Vh99nuvLXEBXqTEBIv61QVGIgjNeWhmeGScQlsaz3ZmOjwar5P9fUPGXVl3TDExfQPQYuiGZJo3N0Ott+aDi9v7JEiTJjcthRYzztHP2+XMEdNv78QwYVCqeWt/BDVUx6frduZGc7Ghqi2iOzjt7pD+yuyBoMzg3srLpt7FT2tJxcdFPm6o1y4wi6Qw4q8T7m9ohk40KbTpdMDie9SRqo5x7usvCkLig80H0yUXcw=
  app: secret-shore-33239
  on:
    repo: namanwahi/BasicWebApp
